name: Send new artifact to main website
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
  push:
    branches: [ master ]

jobs:
  build-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: "Build WasmJS App"
        run: gradle :composeApp:wasmJsBrowserDistribution

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: tarotmeter-wasm
          path: composeApp/build/dist/wasmJs/productionExecutable/
          retention-days: 1

      - name: "Send artifact url"
        run: |
          $runId = "${{ github.run_id }}"
          $repo = "${{ github.repository }}"
          $artifactUrl = "https://github.com/$repo/actions/runs/$runId"
          
          $payload = @{
            event_type = "update-tarotmeter"
            client_payload = @{
              message = $artifactUrl
            }
          } | ConvertTo-Json
          
          Invoke-RestMethod `
            -Uri "https://api.github.com/repos/Axl-Lvy/Axl-Lvy/dispatches" `
            -Method Post `
            -Headers @{
              "Accept" = "application/vnd.github+json"
              "Authorization" = "Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}"
              "X-GitHub-Api-Version" = "2022-11-28"
            } `
            -Body $payload `
            -ContentType "application/json"
